#!/bin/bash



ENVIRONMENT="DEVELOPMENT"
DISTRIBUTION="DEBIAN"

APACHE_DOMAINNAME=${1:-"domain.com"}
APACHE_EMAIL=${2:-"user@example.com"}

INSTALL_MODE="local" 

SITE=${1:-"default"}
PUBLIC_DIRECTORY=${2:-"public"}

VAGRANT_BUILD_LOG=vm_build.log 
VAGRANT_LOG_PATH=$HOME/log

PHP_VERSION="7.0"
USE_NGINX=0 

MYSQL_HOST=localhost
MYSQL_DBNAME="${SITE//\./\_}"
MYSQL_DBUSER="vagrant"
MYSQL_DBPASS="SECRET"
